dataset:
  mode: light
  name: light_small_20

inputs:
  stream: inputs/light-small-20.stream
  params: inputs/light-small-20.params
  tag_delay_file: inputs/light-small-tag-delay-20.xlsx

# Optional
delay_input:
  sheet: in

output:
  directory: outputs/light_small_20

pipeline:
  start_step: C1
  stop_step: C13

crystal:
  space_group: 19
  a: 54.22
  b: 115.78
  c: 117.08
  wavelength: 1.77

selection:
  samples_per_delay: 1
  tmin: -84
  tmax: 550
  random_seed: 123

processing:
  remove_negative_pixels: false
  make_drl_mask: false
  use_drl_mask: false
  generate_hkl_average: true
