dataset:
  mode: dark
  name: dark_clean_2024

inputs:
  stream: inputs/dark-clean-2024.stream
  params: inputs/dark-clean-2024.params

output:
  directory: outputs/dark_clean_2024

pipeline:
  start_step: C1
  stop_step: C9

crystal:
  space_group: 19
  a: 78.1
  b: 78.1
  c: 38.4

advanced:
  h_max: 100
  k_max: 100
  l_max: 100

processing:
  data_type: Intensity
  remove_negative_pixels: false
  generate_hkl_average: true
